In [1]:
import numpy as np

## create one dimensional array (vector)

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
arr = np.array(range(1,28))

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
np.arange(1, 10, 0.5)

# step in range function only interger and can't be float

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.linspace(1, 10, 20)



# linspace can use to make numbers between the range

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
x = np.linspace(1, 10, 10)

In [10]:
y = 2 * x

In [11]:
y

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [12]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [13]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,))

array([0., 0., 0.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
arr.shape

(3, 3)

In [24]:
arr.dtype

dtype('int64')

In [25]:
np.random.rand()

0.12664048335394107

In [26]:
np.random.rand(5)

array([0.36002821, 0.53544707, 0.33239827, 0.60976372, 0.88715159])

In [27]:
np.random.rand(2,3,4)

array([[[0.21365779, 0.86057685, 0.5991852 , 0.04058274],
        [0.03436337, 0.48941406, 0.09691343, 0.99689629],
        [0.63734188, 0.05346922, 0.27883384, 0.4869022 ]],

       [[0.29635784, 0.76267038, 0.96758353, 0.91054682],
        [0.45386588, 0.88461068, 0.72844866, 0.17016239],
        [0.50310091, 0.74843846, 0.48338514, 0.1606385 ]]])

In [ ]:
np.random.randn(3)

array([-0.4002535 ,  0.00527061,  1.41723604])

In [29]:
np.random.randint(2, 10)

8